# Generated by Django 5.2.10 on 2026-05-22 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('pet_name', models.CharField(blank=True, max_length=80)),
                ('pet_type', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кіт'), ('rabbit', 'Кролик'), ('rodent', 'Гризун'), ('bird', 'Птах'), ('other', 'Інше')], max_length=32)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(max_length=8)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Нова'), ('confirmed', 'Підтверджена'), ('done', 'Завершена'), ('cancelled', 'Скасована')], default='new', max_length=16)),
                ('source_page', models.CharField(default='booking', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic.doctor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.service')),
            ],
            options={
                'verbose_name': 'Заявка на запис',
                'verbose_name_plural': 'Заявки на запис',
                'ordering': ['-created_at'],
            },
        ),
    ]
