# Generated by Django 5.2.10 on 2026-05-22 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('clinic', '0003_doctor_bio_and_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('source_page', models.CharField(default='popup', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_leads', to='clinic.service')),
            ],
            options={
                'verbose_name': 'Заявка з попапу',
                'verbose_name_plural': 'Заявки з попапу',
                'ordering': ['-created_at'],
            },
        ),
    ]
