# Generated by Django 5.2.10 on 2026-07-06 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_callbacklead'),
        ('clinic', '0009_alter_advantage_description_alter_advantage_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinic.doctor', verbose_name='Лікар'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='owner_name',
            field=models.CharField(max_length=120, verbose_name='Імʼя власника'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='pet_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Кличка тварини'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кіт'), ('rabbit', 'Кролик'), ('rodent', 'Гризун'), ('bird', 'Птах'), ('other', 'Інше')], max_length=32, verbose_name='Вид тварини'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='preferred_date',
            field=models.DateField(verbose_name='Бажана дата'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='preferred_time',
            field=models.CharField(max_length=8, verbose_name='Бажаний час'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.service', verbose_name='Послуга'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='source_page',
            field=models.CharField(default='booking', max_length=32, verbose_name='Джерело'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('confirmed', 'Підтверджена'), ('done', 'Завершена'), ('cancelled', 'Скасована')], default='new', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='callbacklead',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='callbacklead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='callbacklead',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='callbacklead',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='callbacklead',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_leads', to='clinic.service', verbose_name='Послуга'),
        ),
        migrations.AlterField(
            model_name='callbacklead',
            name='source_page',
            field=models.CharField(default='popup', max_length=64, verbose_name='Джерело'),
        ),
    ]
