# Generated by Django 5.2.10 on 2026-05-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name_line1', models.CharField(default='Ветеринарна', max_length=64, verbose_name='Назва (рядок 1)')),
                ('clinic_name_line2', models.CharField(default='клініка', max_length=64, verbose_name='Назва (рядок 2)')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Слоган')),
                ('address', models.CharField(default='м. Київ, вул. Велика Васильківська, 100', max_length=255, verbose_name='Адреса')),
                ('phone_primary', models.CharField(default='+380441234567', max_length=32, verbose_name='Телефон')),
                ('phone_secondary', models.CharField(blank=True, max_length=32, verbose_name='Телефон 2')),
                ('email', models.EmailField(blank=True, default='info@vetclinic.ua', max_length=254, verbose_name='Email')),
                ('hero_title', models.CharField(default='Турбота про вашого улюбленця цілодобово', max_length=255, verbose_name='Заголовок hero')),
                ('hero_lead', models.CharField(default='Сучасна ветеринарна клініка в центрі Києва. Запис онлайн — за 30 секунд.', max_length=255, verbose_name='Підзаголовок hero')),
                ('hero_stat_number', models.CharField(default='12+', max_length=16, verbose_name='Hero статистика (число)')),
                ('hero_stat_label', models.CharField(default='років допомагаємо тваринам Києва', max_length=120, verbose_name='Hero статистика (підпис)')),
                ('is_open_now', models.BooleanField(default=True, verbose_name='Працюємо зараз')),
                ('trust_label', models.CharField(default='Працюємо зараз', max_length=64, verbose_name='Trust strip')),
                ('hours_label', models.CharField(default='24/7 без вихідних', max_length=64, verbose_name='Години роботи')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
