# Generated by Django 5.2.10 on 2026-05-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_align_hero_mobile_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='м. Київ, вул. Хрещатик 1', max_length=255, verbose_name='Адреса'),
        ),
    ]
