# Generated by Django 5.2.10 on 2026-06-29 09:57

from django.db import migrations, models


def seed_site_blocks(apps, schema_editor):
    SiteSettings = apps.get_model('core', 'SiteSettings')
    SiteBlock = apps.get_model('core', 'SiteBlock')

    from core.block_defaults import BLOCK_CONTENT_TYPES, BLOCK_DEFAULTS
    from core.site_content_registry import all_registry_block_keys, get_block_field_label

    site = SiteSettings.objects.filter(pk=1).first()
    hero_values = {}
    if site is not None:
        hero_values = {
            'hero_title': getattr(site, 'hero_title', '') or BLOCK_DEFAULTS.get(('home', 'hero_title'), ''),
            'hero_lead': getattr(site, 'hero_lead', '') or BLOCK_DEFAULTS.get(('home', 'hero_lead'), ''),
            'hero_stat_number': getattr(site, 'hero_stat_number', '') or BLOCK_DEFAULTS.get(('home', 'hero_stat_number'), ''),
            'hero_stat_label': getattr(site, 'hero_stat_label', '') or BLOCK_DEFAULTS.get(('home', 'hero_stat_label'), ''),
        }

    for page, key in all_registry_block_keys():
        content_type = BLOCK_CONTENT_TYPES.get((page, key), 'text')
        text_default = BLOCK_DEFAULTS.get((page, key), '1' if key.endswith('_section_visible') else '')
        if key in hero_values:
            text_default = hero_values[key]

        SiteBlock.objects.get_or_create(
            page=page,
            key=key,
            defaults={
                'label': get_block_field_label(page, key),
                'content_type': content_type,
                'text_html': text_default,
                'sort_order': 0,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_update_clinic_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('services', 'Послуги'), ('doctors', 'Лікарі'), ('contacts', 'Контакти'), ('site', 'Сайт')], max_length=32, verbose_name='Сторінка')),
                ('key', models.CharField(max_length=64, verbose_name='Ключ блоку')),
                ('label', models.CharField(max_length=128, verbose_name='Назва в адмінці')),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Фото')], default='text', max_length=16, verbose_name='Тип контенту')),
                ('text_html', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='blocks/', verbose_name='Зображення')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Блок контенту',
                'verbose_name_plural': 'Блоки контенту',
                'ordering': ['page', 'sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_site_block_page_key')],
            },
        ),
        migrations.RunPython(seed_site_blocks, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_lead',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_stat_label',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_stat_number',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_title',
        ),
        migrations.CreateModel(
            name='ContactsClinicInfoSettings',
            fields=[],
            options={
                'verbose_name': 'Контакти — Клініка',
                'verbose_name_plural': 'Контакти — Клініка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='ContactsFormSettings',
            fields=[],
            options={
                'verbose_name': 'Контакти — Форма',
                'verbose_name_plural': 'Контакти — Форма',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='ContactsMapSettings',
            fields=[],
            options={
                'verbose_name': 'Контакти — Карта',
                'verbose_name_plural': 'Контакти — Карта',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='ContactsPageHeaderSettings',
            fields=[],
            options={
                'verbose_name': 'Контакти — Шапка',
                'verbose_name_plural': 'Контакти — Шапка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='DoctorsPageHeaderSettings',
            fields=[],
            options={
                'verbose_name': 'Лікарі — Шапка',
                'verbose_name_plural': 'Лікарі — Шапка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='FooterSocialSettings',
            fields=[],
            options={
                'verbose_name': 'Footer — Соцмережі',
                'verbose_name_plural': 'Footer — Соцмережі',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeAdvantagesSettings',
            fields=[],
            options={
                'verbose_name': 'Головна — Переваги',
                'verbose_name_plural': 'Головна — Переваги',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeDoctorsPreviewSettings',
            fields=[],
            options={
                'verbose_name': 'Головна — Лікарі',
                'verbose_name_plural': 'Головна — Лікарі',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeHeroSettings',
            fields=[],
            options={
                'verbose_name': 'Головна — Hero',
                'verbose_name_plural': 'Головна — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeServicesPreviewSettings',
            fields=[],
            options={
                'verbose_name': 'Головна — Послуги',
                'verbose_name_plural': 'Головна — Послуги',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='ServicesPageHeaderSettings',
            fields=[],
            options={
                'verbose_name': 'Послуги — Шапка',
                'verbose_name_plural': 'Послуги — Шапка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='TrustStripSettings',
            fields=[],
            options={
                'verbose_name': 'Trust strip',
                'verbose_name_plural': 'Trust strip',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
    ]
