# Generated by Django 5.2.10 on 2026-06-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactsclinicinfosettings_contactsformsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='м. Київ, вул. Ірпінська, 67б', max_length=255, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='clinic_name_line1',
            field=models.CharField(default='ветеринарна клініка', max_length=64, verbose_name='Назва (рядок 1)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='clinic_name_line2',
            field=models.CharField(default='Фенікс', max_length=64, verbose_name='Назва (рядок 2)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hours_label',
            field=models.CharField(default='Цілодобово', max_length=64, verbose_name='Години роботи'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_primary',
            field=models.CharField(default='+380933839933', max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_secondary',
            field=models.CharField(blank=True, default='+380983839033', max_length=32, verbose_name='Телефон 2'),
        ),
    ]
