# Generated by Django 5.2.10 on 2026-07-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sitesettings_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='brand/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='trust_label',
            field=models.CharField(default='Працюємо зараз', max_length=64, verbose_name='Смуга довіри'),
        ),
    ]
