# Generated by Django 5.2.10 on 2026-07-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_logo_alter_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactspageheadersettings',
            options={'verbose_name': 'Контакти — Заголовок', 'verbose_name_plural': 'Контакти — Заголовок'},
        ),
        migrations.AlterModelOptions(
            name='doctorspageheadersettings',
            options={'verbose_name': 'Лікарі — Заголовок', 'verbose_name_plural': 'Лікарі — Заголовок'},
        ),
        migrations.AlterModelOptions(
            name='footersocialsettings',
            options={'verbose_name': 'Футер — Соцмережі', 'verbose_name_plural': 'Футер — Соцмережі'},
        ),
        migrations.AlterModelOptions(
            name='homeherosettings',
            options={'verbose_name': 'Головна — Банер', 'verbose_name_plural': 'Головна — Банер'},
        ),
        migrations.AlterModelOptions(
            name='servicespageheadersettings',
            options={'verbose_name': 'Послуги — Заголовок', 'verbose_name_plural': 'Послуги — Заголовок'},
        ),
        migrations.AlterModelOptions(
            name='truststripsettings',
            options={'verbose_name': 'Смуга довіри', 'verbose_name_plural': 'Смуга довіри'},
        ),
    ]
