# Generated by Django 5.2.10 on 2026-05-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('clock', 'Годинник'), ('shield', 'Щит'), ('star', 'Зірка'), ('heart', 'Серце')], default='clock', max_length=32)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_alt', models.BooleanField(default=False, help_text='Помаранчева іконка')),
            ],
            options={
                'verbose_name': 'Перевага',
                'verbose_name_plural': 'Переваги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('specialization', models.CharField(max_length=160)),
                ('experience_years', models.PositiveSmallIntegerField()),
                ('initials', models.CharField(blank=True, max_length=8)),
                ('photo', models.ImageField(blank=True, upload_to='doctors/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Лікар',
                'verbose_name_plural': 'Лікарі',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('short_description', models.CharField(max_length=120)),
                ('full_description', models.TextField()),
                ('price_hint', models.CharField(blank=True, max_length=64)),
                ('icon', models.CharField(choices=[('stethoscope', 'Стетоскоп'), ('syringe', 'Шприц'), ('scissors', 'Ножиці'), ('scan', 'Діагностика'), ('tooth', 'Зуб'), ('ambulance', 'Швидка')], default='stethoscope', max_length=32)),
                ('bullets', models.JSONField(blank=True, default=list)),
                ('is_urgent', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['order', 'name'],
            },
        ),
    ]
