# Generated by Django 5.2.10 on 2026-05-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_doctor_rating_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Коротка біографія'),
        ),
    ]
