# Generated by Django 5.2.10 on 2026-06-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_remove_ct_from_visual_diag'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
    ]
