# Generated by Django 5.2.10 on 2026-07-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_advantage_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='description',
            field=models.CharField(max_length=160, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='icon',
            field=models.CharField(choices=[('clock', 'Годинник'), ('shield', 'Щит'), ('star', 'Зірка'), ('heart', 'Серце')], default='clock', max_length=32, verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='is_alt',
            field=models.BooleanField(default=False, help_text='Помаранчева іконка', verbose_name='Помаранчева іконка'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveSmallIntegerField(verbose_name='Досвід (роки)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='initials',
            field=models.CharField(blank=True, max_length=8, verbose_name='Ініціали'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='doctors/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=160, verbose_name='Спеціалізація'),
        ),
        migrations.AlterField(
            model_name='service',
            name='bullets',
            field=models.JSONField(blank=True, default=list, verbose_name='Маркований список'),
        ),
        migrations.AlterField(
            model_name='service',
            name='full_description',
            field=models.TextField(verbose_name='Повний опис'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('stethoscope', 'Стетоскоп'), ('syringe', 'Шприц'), ('scissors', 'Ножиці'), ('scan', 'Діагностика'), ('tooth', 'Зуб'), ('video', 'Онлайн')], default='stethoscope', max_length=32, verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Терміново'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_hint',
            field=models.CharField(blank=True, max_length=64, verbose_name='Ціна (підказка)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.CharField(max_length=120, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
    ]
